spring:
  flyway:
    enabled: true
    user: root
    password: flashcards
    url: jdbc:mysql://flashcards-db.crgqm4weayav.eu-north-1.rds.amazonaws.com:3306/flashcards?createDatabaseIfNotExist=true
    schemas: flashcards
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    username: root
    password: flashcards
    url: jdbc:mysql://flashcards-db.crgqm4weayav.eu-north-1.rds.amazonaws.com:3306/flashcards?createDatabaseIfNotExist=true
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    id: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
    verify:
      host: ${VERIFY_EMAIL_HOST}
server:
  port: '8182'

token:
  secret.key: '8472B4B6250655367566B5970337336763979244226452948404D635166546A'
  valid.time: '86400000'
aws:
  access:
    key:
      id: ${YOUR_ACCESS_KEY_ID}
  secret:
    access:
      key: ${YOUR_SECRET_ACCESS_KEY}
