#email config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: youremail
EMAIL_PASSWORD: yourpasword
VERIFY_EMAIL_HOST: http://localhost:8182

#Server
ACTIVE_PROFILE: dev

#Database
DB_USER: root
DB_PASSWORD: flashcards

#aws
YOUR_ACCESS_KEY_ID:
YOUR_SECRET_ACCESS_KEY:
